# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use local action
        uses: ./.github/actions/test-a
        with:
            who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }} 
        shell: bash


 #     - name: Check out repository
 #       uses: actions/checkout@v2
 #     - name: Use local my-action
 #       uses: ./.github/actions/my-action
#Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/ActionsTest/ActionsTest/.github/actions/FirstAction'. 
#Did you forget to run actions/checkout before running your local action?
